/**********************************************************************
*These solidity codes have been obtained from Etherscan for extracting
*the smartcontract related info.
*The data will be used by MATRIX AI team as the reference basis for
*MATRIX model analysis,extraction of contract semantics,
*as well as AI based data analysis, etc.
**********************************************************************/
pragma solidity ^0.4.0;
contract Digitaalisuusreflektiot {

/*
Digitaalisen yhteiskunnan rajapinnoilla
Nämä reflektiot kuuluvat osana Helsingin yliopistolla syksyllä 2017 järjestetyn ”Digitaalisen yhteiskunnan rajapinnoilla” -kurssin suorittamiseen. Kurssin aiheena oli teknologiavälitteinen sosiaalinen toiminta eri digitaalisilla areenoilla. Tarkoitus on reflektoida opittua, käyttää kurssikirjallisuutta sekä muuta materiaalia ja edistää ymmärrystä verkon luonteesta kulttuurisena ja sosiaalisena muotona. Reflektiot esitetään luentokohtaisesti kuudesta luennosta (luennot 1-6).


30.10. INTROLUENTO: MITÄ ON DIGITAALINEN YHTEISKUNTATIEDE?

Aluksi taustoituksena on hyvä mainita, että elämme erityisen suuren murroksen aikakautta. Tätä murrosta on kutsuttu toiseksi kommunikaatiovallankumoukseksi; noin sata vuotta sitten tapahtunut ensimmäinen kommunikaatiovallankumous perustui hierarkiaan (organisaatiot, infrastruktuuri ja massamedia). Nyt tapahtuva toinen kommunikaatiovallankumous perustuu joustavaan verkostorakenteeseen (verkko korvaa perinteisiä viestintä- ja logistiikkaväyliä, segmentoitunut ja henkilökohtainen kommunikaatio) (van Dijk 2012). Murros on synnyttänyt uusia tieteenaloja, kuten esimerkiksi Internetin tutkimuksen (Internet studies), joka on nopeasti laajeneva monitieteinen tieteenala (Dutton 2014). Monitieteisyydestä puhuttiin myös luennoilla; ne korostivat tarvetta humanististen painotusten vahvistamiseen.
”Kuluttajakansalaiset datataloudessa”-luennon aiheena oli kuluttajakansalaisen arki datataloudessa ja digitalisoitumiskehitys sekä muutokset kuluttajan roolissa. Datakansalainen-sana herättää ajatuksen alamaisuudesta; toimimme suurten datajättien ehtojen mukaan ja meillä on näennäinen kyky vaikuttaa esimerkiksi likettämällä, klikkaamalla tai googlaamalla, mutta meillä ei varsinaisesti ole mahdollisuutta vaikuttaa algoritmeihin tai datajättien päätöksentekoon. Tämä asettaa datakansalainen-käsitteen kyseenalaiseksi. Elämmekö enemmänkin autoritaarisessa näennäisdatademokratiassa, jossa meille annetaan illuusio mahdollisuudesta vaikuttaa asioihin, vaikka todellisuudessa olemme jättien alamaisia?
Teknologinen kehitys on muovannut kuluttajan roolia vastaanottajasta informaation prosessoijaksi, sisällöntuottajaksi ja edelleen arvontuotannon lähteeksi. Tämän kehityksen seurauksena meistä on tullut älykkäitä sensoreita joista kerätään paljon dataa, josta korvaukseksi voimme käyttää yritysten tarjoamia palveluja. Hyödyt ovat todennäköisesti suurempia kuin haitat, koska pysymme kuitenkin näiden palveluiden käyttäjinä. Emme välttämättä kuitenkaan tiedä, miten ja millaista dataa meistä kerätään. Luennolla mainittiin muun muassa nukkevakooja, joka kerää lasten elämästä tietoa. Nuken ostaja ei välttämättä tule edes ajatelleeksi tai kiinnittäneeksi huomiota siihen, mitä nukke tekee. Kaikki datankeruu ei kuitenkaan välttämättä ole huono asia; nukkevakooja voi esimerkiksi oppia reagoimaan lapsen eleisiin tai puheeseen, millä voi olla yhteys lapsen parempaan viihtyvyyteen ja mahdollisuuteen jatkokehittää tuotetta, jolloin datankeruusta on hyötyä kaikille osapuolille. Rifkin on luennon mukaan esittänyt ajatuksen yksityisyydensuojan menettämisestä. Hyvä kysymys on, näemmekö tai tiedämmekö kuinka paljon dataamme hyödynnetään yritysten toimesta. 
”Digitaalinen kulttuuri ja sosiaalisuus”-luento esitteli digitaalisen kulttuurin ja sosiaalisuuden tutkimuksellisia lähtökohtia. Aiheena olivat muun muassa kulttuurin muutokset ja disruptiot. Mielestäni luento näki digitaalisen kulttuurin kriittisessä valossa. Kauhukuvia ovat esimerkiksi sitoutuminen itsemittausteknologiaan koneen osaksi ja vanhusten ja lasten sysääminen hoivarobottien hoidettavaksi. En kuitenkaan sanoisi, että riippuvuus itsemittausteknologiasta olisi pelkästään huono asia. Itsemittausteknologia saattaa esimerkiksi pelastaa ihmisen burnoutilta tai ennaltaehkäistä sairauden syntymistä, koska itsemittausteknologia tunnistaa heikkoja signaaleja ihmisen kunnon ja terveyden heikkenemisestä ennen kuin tilanne on mennyt liian pitkälle. 
Kulttuurin muutosta tarkastellaan myös kurssin oheiskirjallisuudessa; esimerkiksi van Dijk (2012) esittää The Network Society -kirjassa huolen sosiaalisen ympäristön saastumisesta. Uuden kommunikaatioteknologian on ajateltu olevan haitallista sosiaaliselle vuorovaikutukselle, mutta vastakkaisen näkemyksen mukaan kommunikaatioteknologia laajentaa face-to-face-ulottuvuutta sen sijaan, että se korvaisi sen. Baymin (2015) mukaan emme puhu dystopiasta enää puhelinteknologian osalta: teknologiat ikään kuin normalisoituvat (domesticate, teknologia kesytetään). Tämä on prosessi, jossa villistä teknologiasta kesytetään päivittäinen asia. (Baym 2015.) Nykyiset kauhukuvat voivat tässä mielessä olla luonnollinen osa siirtymävaihetta ennen teknologian omaksumista luonnolliseksi osaksi arkea. Yhtäältä uudet yhteydenpidon muodot on nähty uhkana yhteydenpidolle ja ihmistenvälisille suhteille, mutta toisaalta ne tarjoavat mahdollisuuksia muodostaa yhteyksiä uusiin ihmisiin sekä mahdollisuuksia vahvistaa ihmissuhteita.
Luennolla esitettiin kahteen kertaan ajatus muutoksesta deittailukulttuurissa; deittailusta on tullut nettideittailun myötä entistä intensiivisempää ja paikkaperusteisempaa. Perehdyin nettideittailun kulttuuria muokkaaviin vaikutuksiin tarkemmin kurssikirjallisuuden kautta. Duttonin (2014) kirja Handbook of Internet Studies tarkastelee nettideittailua kokonaisen artikkelin laajuudessa: “The Study of Online Relationships and Dating”. Artikkelin mukaan nettideittailussa ollaan selektiivisempiä ja suunnitelmallisempia sen suhteen, mitä itsestä kerrotaan vastapuolelle. On myös huomattu, että nettideittailijat voivat systemaattisesti vääristää kuvaa itsestään parantaakseen mahdollisuuksiaan deittailumarkkinoilla. (Dutton 2014.) van Dijkin mukaan deittailu muuttuu liiketoiminnan kaltaiseksi tietyillä ominaisuuksilla varustetun henkilön etsinnäksi. Tietyt ominaisuudet ja asenteet omaava henkilö on helpompi löytää nettideittailun kautta. Suhde on helppo korvata toisella. Suhteet voivat lyhentyä, ja traditionaaliset flirttailun tavat heikentyvät. (van Dijk 2012, s. 264.) Tinderiä on mediassa haukuttu siitä, että se edistää kertakäyttöistä deittailukulttuuria (ks. Guardian 16.08.2015). Lisäksi Internetissä virtuaalisesti luodut ihmissuhteet eivät välttämättä tunnu oikeilta ihmissuhteilta (Baym 2015). Uskoisin silti, että vaikka nettideittailuun liittyy tiettyjä ongelmakohtia, ilmiö ei ole niin yksiselitteinen ja siihen liittyy sekä haittoja että hyötyjä.
Esimerkkejä kulttuurisesta muutoksesta voidaan löytää loputtomiin. Kirjaa lukiessani oivalsin, että myös sellainen asia kuin esimerkiksi sodankäynti on muutoksessa. Sodankäynti on siirtymässä osittain verkkoon (ns. cyber-war); pyrkimyksenä on aiheuttaa vahinkoa tai häiriötä toisen maan verkossa. Varsinaista laajamittaista cyber-sotaa ei ole ainakaan vielä ollut, mutta tiettyjen maiden hallitukset ovat olleet osallisina cyber-hyökkäyksissä. (van Dijk 2012.) 

Lähteet
Baym, Nancy (2015) Personal Relations in the Digital Age.
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Dutton, William (2014) Handbook of Internet Studies.
Guardian 16.08.2015: Is Tinder really creating a ‘dating apocalypse’? Viitattu  13.12.2017. Saatavissa: https://www.theguardian.com/technology/2015/aug/16/tinder-app-creating-dating-apocalypse-twitter-storm 

6.11. IDENTITEETTI, ADDIKTIO JA TEKNOLOGIA

Toisen luennon ensimmäisen osuuden aiheena olivat addiktiot. Käyttäjäkokemus ei ole ainoa informaatioteknologian kehitystä ohjaava tekijä, vaan sen lisäksi ohjelmistot ja laitteet suunnitellaan siten, että käyttäjä addiktoituu niihin. “'Our minds can be hijacked': the tech insiders who fear a smartphone dystopia”-artikkeli tarjoaa esimerkkejä addiktoivasta designista; Facebookin “tykkää”-toiminto tuottaa pseudomielihyvää. Sosiaalisen median toimintalogiikkaa voidaan verrata uhkapelaamiseen: punaisten ikonien klikkaaminen on kuin osallistuisi arpajaisiin, alaspäin pyyhkäisyyn perustuva päivitystoiminto on kuin hedelmäpeli. (Quardian 6.10.2017.) Näitä ominaisuuksia ei välttämättä tule ajatelleeksi, koska käyttäjä ei välttämättä tiedosta ohjelmistokehityksen motiiveja. Tietoisuus ongelmista on kuitenkin noussut yhteiskunnalliseen keskusteluun mediassa, esimerkiksi Helsingin sanomat ja YLE ovat viime viikkoina kirjoittaneet sosiaalisen median haitallisuudesta.
Sosiaalisen median psykologisista seurauksista käyttäjille ja yhteiskunnalle ollaan oltu huolissaan; yksilötasolla voi seurauksena olla keskittymiskyvyn heikkeneminen, yhteiskunnan kannalta seurauksena on niin sanottu huomiotalous oireineen (Quardian 6.10.2017). Huomiotaloudessa kohut saavat julkisuutta. Kun ajatellaan että perinteisesti median rooli on ollut sivistää kansalaisia, kohujen ja mielihyväkeskeisyyden vaikutus yleiselle moraalille voi olla päinvastainen. Addiktioista puhuttiin luennolla lähinnä negatiivisessa valossa. Mielihyvän tavoittelu ja addiktiot voivat joissain tilanteissa olla eteenpäin ajava voima, jos ne kohdistuvat olennaisiin asioihin, jotka vievät yksilöä elämässä eteenpäin; esimerkiksi yksilö voi olla addiktoitunut opiskeluun tai työhön. Ongelma voikin olla se. että ihmiset keskittyvät vääriin asioihin, kuten esimerkiksi kissavideoihin. Ei tosin ole aiheellista väittää, että kissavideot olisivat pelkästään huono asia. 
Luennon sokerihiiriesimerkissä ja Quardianin artikkelissa väitettiin, että addiktioiden vuoksi tarvitaan keinotekoisia sääntöjä. Olen asiasta eri mieltä. Merkityksellisen tekemisen etsiminen voi mahdollisesti auttaa; kun yksilöllä on merkityksellistä tekemistä, aikaa addiktioille ei ole. Lisäksi olen eri mieltä siitä että elämän pitäisi jatkuvasti olla elämyksellistä tai yllätyksellistä. Luennolla mainittiin teoria, jonka mukaan nautinto on opittu ominaisuus; mielestäni elämyshakuisuus ja tarve yllätyksellisyyteen ovat vastaavasti opittuja ominaisuuksia. Mediassa on puhuttu digiähkystä ja halusta luopua älypuhelimesta (ks. YLE 20.06.2017); addiktoitumisen ongelma näyttäisi olevan todellinen, vaikka sitä tässä vähättelen.
“Identiteetti ja teknologia”-luennolla tarkasteltiin identiteettiä sosiaalisen median aikakaudella. Voin samaistua sosiaalisen median aiheuttamaan identiteettikonfliktiin; sosiaaliseen mediaan on vaikea kirjoittaa, koska viestin tulee olla sopiva kaikille kavereille. Uskin ja Lampisen (2016) artikkeli sosiaalisista normeista ja itseilmaisusta sosiaalisen median sivuilla tarjoaa näkemyksiä siitä, miten joudumme tekemään profiilityötä ja sopeutumaan sosiaalisiin normeihin. Artikkelin löydös oli se, että sosiaalisessa mediassa pyritään autenttisuuteen. Baym (2015) esittää kirjassaan vastakkaisen näkemyksen, jonka mukaan internetissä voi teeskennellä ja valehdella, koska digitaalinen media erottaa minuuden kehosta. Internet tarjoaa yksilölle mahdollisuuksia  kokeilla erilaisia identiteettejä ja olla erilainen yksilö eri alustoilla; esimerkiksi musiikkifani lasf.fm:ssä ja akateeminen henkilö LinkedIn:ssä. Huijaamisen mahdollisuudesta huolimatta kirjan mukaan ihmiset ovat rehellisempiä netissä kuin kasvotusten. Yhtäältä internet mahdollistaa valehtelemisen ja teeskentelyn, mutta toisaalta internetissä on mahdollista esittää vapaammin todellista minuuttaan ja tässä mielessä internet voi olla vapauttava. (Baym 2015.)
Luennolla spekuloitiin lasten ja nuorten alkoholin käytön vähentymisen syitä: johtuisiko siitä että pelkää joutuvansa someen, vai houkuttaako terveystrendi? Itselleni tuli mieleen kolmas mahdollinen selitys; nuorten aika menee internetissä ja sosiaalisessa mediassa, addiktiot kohdistuvat peleihin ja tietokoneella olemiseen, jolloin alkoholi menettää merkitystään addiktion kohteena ja ajanvieton muotona.
Snapchat toimii hyvänä case-esimerkkinä addiktoivasta ohjelmistokehityksestä. Suomen kuvalehti (01.12.2017) esittelee Snapchatin toteutusta; Snapchat on sosiaalinen media, jonka Streak-luku osoittaa kuinka monta päivää kaverukset ovat yhtäjaksoisesti viestitelleet toisilleen. Luku nollaantuu jos viestittelyyn tulee yli vuorokauden tauko, tiimalasi varoittaa nollaantumisesta käyttäjälle; tällä designilla Snapchat pyrkii koukuttamaan käyttäjän jatkamaan yhteydenpitoa kaveriensa kanssa. Yhteydenpito on ikään kuin sosiaalinen peli, jossa suosion mittarina on Snapchatin Streak-luku. Luku voi aiheuttaa riippuvuutta, mutta toisaalta se edistää sosiaalisten suhteiden muodostumista, verkostoitumista ja itsevarmuutta. (Suomen kuvalehti 01.12.2017.) Sosiaalisen median hyvyys tai huonous riippuu näin ollen näkökulmasta. Amerikassa tehdyn tutkimuksen mukaan internetin käyttäjät pitävät enemmän yhteyttä lähimmäisiinsä, kavereihin ja kollegoihin verrattuna niihin jotka eivät käytä internettiä (Baym 2015, s. 141). 

Lähteet
Baym, Nancy (2015) Personal Relations in the Digital Age.
Quardian 6.10.2017: 'Our minds can be hijacked': the tech insiders who fear a smartphone dystopia. Viitattu  13.12.2017. Saatavissa: https://www.theguardian.com/technology/2017/oct/05/smartphone-addiction-silicon-valley-dystopia
Suomen kuvalehti 01.12.2017: Snapchat kannustaa teinejä pitämään ystavyyssuhteita yllä kellon ympäri. Viitattu  13.12.2017. Saatavissa: https://suomenkuvalehti.fi/jutut/kotimaa/snapchat-kannustaa-teineja-pitamaan-ystavyyssuhteita-ylla-kellon-ympari/?shared=996419-98c31999-999
Uski, S., & Lampinen, A. (2016). Social norms and self-presentation on social network sites: Profile work in action. New media & society, 18(3), 447-464.
YLE 20.06.2017: "Hylkäsin Facebookin, luovuin älypuhelimesta, vaihdoin vanhaan” – kolme tarinaa siitä, miten digiähkyn voi selättää. Viitattu  13.12.2017. Saatavissa: https://yle.fi/aihe/artikkeli/2017/06/20/hylkasin-facebookin-luovuin-alypuhelimesta-vaihdoin-vanhaan-kolme-tarinaa-siita

13.11. NÄKÖKULMIA POLITIIKKAAN JA TEKNOLOGIAAN

”Demokratian tukeminen teknologialla”-luennolla teknologian vaikutuksesta politiikkaan oltiin pessimistisiä; luennolla mainittiin muun muassa valeuutiset ja verkkosivujen (esim. Kansalaisaloite.fi) toimimattomuus. Lisäksi demokratian kannalta olennainen kysymys on, onko internet vapauden vai kontrollin teknologia? van Dijk (2012) käsittelee aihetta kirjassaan. Hänen mukaansa internet voi toimia demokraattisena työkaluna ja vähentää riippuvuutta massamediasta. Käyttäjistä tulee sisällöntuottajia ja osallistujia. Politiikasta tulee entistä enemmän verkottunutta; internet korvaa televisiota ja lehdistöä poliittisen keskustelun areenana. Internet ei kuitenkaan ole demokraattinen, koska sekä autoritaariset että demokraattiset valtiot pyrkivät kontrolloimaan sitä. (van Dijk 2012.) Demokratian tukeminen kontrollin teknologialla sisältää vivahteita autoritäärisyydestä, jossa datajätit ja maiden hallitukset hallitsevat ja manipuloivat kansalaisten ajatuksia ja mielipiteitä. Vapauden teknologiana internet on myös ongelmallinen, sillä vapaa ja sääntelemätön ympäristö on datajättien etu. 
Etsin internetistä lisätietoa siitä, millaisia valeuutisia maailmalla on liikkunut ja mitä seurauksia niillä on ollut. Yhtenä esimerkkinä voidaan mainita Intiassa levinneet valheelliset WhatsApp-viestit, joiden mukaan miesjoukko kaappasi lapsia; viestit johtivat seitsemän ihmisen kuolemaan (BBC 24.07.2017). Tämä esimerkki osoittaa sen, että vapaasta tiedonvälityksestä ei aina seuraa pelkkää hyvää.
Kurssilukemiston “Do Artifacts Have Politics?”-artikkelissa esitettiin kaksi tapaa, joilla artefaktit voivat toimia poliittisesti (Winner 1980). Artefaktit tuottavat joillekin osapuolille poliittisia hyötyjä, toisille haittoja. Siltojen osalta on helppo huomata, että ne rajoittavat bussien mahdollisuuksia liikkua. Siltoja suunnitellessa seuraukset ovat usein myös odotettavissa. Algoritmien poliittiset seuraukset tuntuvat siltoihin verrattuna hankalalta hahmottaa. Niiden osalta emme tiedä, miten ne on suunniteltu ja kun algoritmissa on erittäin suuri määrä muuttujia, edes niiden suunnittelija ei voi varmuudella tietää mitä seurauksia niillä on. Algoritmeja suunniteltaessa odottamattomien seurausten mahdollisuus voi näin ollen olla suuri. Joissain tilanteissa, esimerkiksi kun viestin pituus on rajoitettu 160 merkkiin, seuraukset ovat selkeämmin nähtävissä.
Luennolla mainittiin käsitteet teknologinen determinismi ja teknologinen sosiaalinen konstruktionismi. Perehdyin näihin käsitteisiin tarkemmin Baymin (2015) kirjan kautta. Teknologisen determinismin mukaan teknologia ja laitteet muuttavat meitä. Huolenaiheena on ollut muun muassa internet-teknologian vaikutus älykkyyteen ja muistamiskykyyn. Teknologisen determinismin näkökulmassa esitetään, että negatiiviset vaikutukset voidaan poistaa teknologiaan kehittämällä. Teknologian sosiaalinen konstruktionismis mukaan ihmisillä on valta; ihmiset ovat muutoksen agentteja, joiden toimista teknologiat syntyvät. (Baym 2015.) Aiemmilla luennoilla puhuimme lähinnä teknologiasta luopumisesta tai sen käytön vähentämisestä, joka on vastakkainen näkemys Baymin esittämään ajatukseen ongelmien ratkaisemisesta teknologiaa kehittämällä. Ongelmien ratkaiseminen teknologiaa kehittämällä on näkemys joka liittyy teknologiseen determinismiin, joka ei välttämättä näe koko totuutta. Totuus on näiden kahden edellä esitetyn käsitteellisten ääripäiden välissä.
”Näkökulmia politiikkaan”-luento tarkasteli politiikkaa internet-ajan kontekstissa. Internet mahdollistaa uudenlaista vaalikeskustelua, mutta seurauksena ovat myös kuplat. Baymin kirjan mukaan poliittinen toiminta verkossa lisää polarisaatiota sen sijaan, että se synnyttäisi keskustelua eri näkökulmien välillä. Verkkoyhteisöt ovat homogeenisiä ja ne rajoittavat pääsyä monipuolisiin näkökulmiin. (Baym 2015.) Kuplat eivät kuitenkaan ole pelkästään ongelma, vaan niihin liittyy myös hyötyjä. Kauppalehden (30.11.2017) jutussa “Siilojen, kuplien ja kuppikuntien puolesta” esitetään, että ajatusten kehittyminen tarvitsee eristyneisyyttä. van Dijk (2012) esittää kirjassaan pienten maailmojen lain (The law of small worlds), jonka mukaan verkossa on helppo saavuttaa muita; maailma on pieni ja kaikki ovat lähellä. Voisiko ihmiskontaktien ylläkylläisyyteen liittyä sama dynamiikka kuin informaation yltäkylläisyyteen? Mahdollisesti olemme entistä valikoivampia ihmiskontaktien suhteen, kun niitä on tarjolla erittäin suuri määrä. Keskustelun polarisoituminen on näkynyt viime aikoina sosiaalisessa mediassa, kuten esimerkiksi luennolla mainitulla Lisää kaupunkia Helsinkiin -palstalla. Vaikka internetillä on politiikan edistämisen työkaluna omat ongelmansa, sen käyttöä pyritään lisäämään ihmisen osallistumisen työkaluna. Ristiriitoja aiheuttavat lisäksi erilaiset näkökulmat; hallinto, nörtti ja kansalainen voivat olla eri mieltä siitä, miten virtuaaliset poliittiset areenat pitäisi toteuttaa. Kun sivujen suunnittelu tehdään hallinnon näkökulmasta, hallinnon arvot ohjaavat ja rajaavat sitä, miten kansalaiset voivat osallistua.
“Re-constructing digital democracy: An outline of four ‘positions’”-artikkelissa esitettiin neljä demokratian positiota (ks. Dahlberg 2011). Esimerkiksi “liberal-individualistic digital democracy” on riippuvainen siitä, miten internet-sivut (esim. Kansalaisaloite.fi) on rakennettu. “Deliberative digital democracy” puolestaan riippuu siitä, millaisia julkisuuden alustoja kansalaisille on tarjolla, ja “Counter-publics digital democracy” vastaavasti riippuu siitä minkälaisten verkkosivujen sallitaan toimia. Handbook of Internet Studies -kirjan luvun 21 artikkelissa ”Analyzing freedom of expression online: Theoretical, empirical and normative contributions” tuodaan esille, että valtio voi sensuroida tai sulkea haluamiaan nettisivuja ja palvelimia (Dutton 2014). Demokratian positiot eivät näissä olosuhteissa voi toimia täysin vapaasti. Bitcoin-kryptovaluutta on hyvä esimerkki “Autonomist Marxist digital democracy”:stä. Kryptovaluutat mahdollistavat itseorganisoidun osallistumisen, joka on irrallaan keskitetyistä järjestelmistä (mm. suuryrityksistä, pankeista, valtioista). 
Handbook of Internet Studies -kirjan “Digital Inequality”-luvussa tarkastellaan digitaalisen teknologian epätasa-arvoisuutta. Yhtäältä eriarvoisuutta on väestön eri segmenttien välillä sekä globaalisti maiden välillä. Lisäksi eriarvoistumista voivat lisätä eritasoiset ICT-taidot sekä erot sosioekonomisessa asemassa. Toisaalta internet voi parantaa ihmisten mahdollisuuksia saada taitoja ja tietoa, joilla he voivat parantaa osaamistaan ja asemaansa työmarkkinoilla. (Dutton 2014.) Epätasa-arvoisessa verkkoyhteiskunnassa voi syntyä informaatioeliitti, jonka ympärillä on osallistuva enemmistö. Osa ihmisistä on suljettu ulkopuolelle. (van Dijk 2012, s. 206.) Internet on mielestäni kyseenalainen poliittisen vaikuttamisen edistäminen kanava, koska se sulkee osan ihmisistä ulkopuolisiksi. Kaikki suomalaiset eivät käytä internetiä, ja ne jotka eivät käytä tai ne joilla ei ole siihen riittäviä taitoja, ovat eriarvoisessa asemassa suhteessa muihin.

Lähteet
Baym, Nancy (2015) Personal Relations in the Digital Age.
BBC 24.07.2017: The people trying to fight fake news in India. Viitattu  13.12.2017. Saatavissa: http://www.bbc.com/news/world-asia-india-40657074
Dahlberg, L. (2011). Re-constructing digital democracy: An outline of four “positions.” New Media & Society, 13(6), 855–872.
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Dutton, William (2014) Handbook of Internet Studies.
Kauppalehti 30.11.2017: Siilojen, kuplien ja kuppikuntien puolesta. Viitattu  13.12.2017. Saatavissa: https://www.kauppalehti.fi/uutiset/siilojen--kuplien-ja-kuppikuntien-puolesta/XmgGKB4Y
Winner, L. (1980). Do artifacts have politics? Daedalus, 121-136. 


20.11. SOSIAALINEN VUOROVAIKUTUS JA YHTEISTOIMINTA VERKKOALUSTOILLA

Handbook of Internet Studies -kirjan ”Network Societies and Internet Studies: Rethinking time, space, and class” artikkelissa esitetään, että ajatukset yhtenäisestä globaalista tietoyhteiskunnasta eivät toimi käytännössä, vaan sen sijaan verkkoon on syntymässä useampia verkottuneita yhteiskuntia, joiden kulttuurinen kirjo on laaja (Dutton 2014). The Network Society kirjan mukaan puhumme verkkoyhteiskunnasta, mutta silti yhteiskunnassa on entistä enemmän fragmentoitumista, individualisaatiota, vapautta ja itsenäisyyttä. Verkosto ja yksilö ovat kolikon kaksi eri puolta; maailma ei koskaan ole ollut vapaampi, mutta se ei myöskään ole koskaan ollut näin yhteenkietoutunut. Yhä useampi organisaatio on riippuvainen internetistä. (van Dijk 2012.) Oheiskirjallisuudessa mainitaan lisäksi siirtymä verkkoyhteisöistä individualistisiin verkostoihin, joissa jokainen yksilö on oman verkostonsa keskipiste (Baym 2015).
“Sosiaalisten rajojen hallinta yhteisöpalveluissa”-luennolla tarkasteltiin alustapalveluja ja jakamistaloutta. Jakamistalouden osalta keskustelu on usein ollut negatiivista; haluamme omistaa sen mitä meillä on, vaikka auto seisoo käyttämättä suurimman osan ajasta. Airbnb-tutkimus osoitti, että jakamistalous voi olla rahanvaihdon lisäksi myös sosiaalista vaihtoa josta on hyötyä sosiaaliselle elämälle (Lampinen & Cheshire 2016). Kun painopiste siirtyy sosiaaliseen vaihtoon, siitä voi seurata ihmisten syrjintää, koska ihmisillä on taipumus suosia itsensä kaltaisia ihmisiä. Toiminnan sujuvoittamiseksi jakamistaloudessa tarvitaan selkeitä sääntöjä, joiden määrittämisen ja seurannan osalta alustatoimijat ovat tärkeässä asemassa. Alustatoimijan läsnäolo ratkaisee myös luennolla mainitun kiitollisuuden velkaan jäämisen ongelman. Lisäksi luennolla todettiin, että alustaa tarvitaan saatavilla olevien palvelujen kohdentamiseen. Vaikka luennolla korostettiin alustan olemassaolon tärkeyttä, toiminta on mahdollista järjestää lohkoketjun kautta ilman välittäjäorganisaatiota tai muuta kolmatta osapuolta. Esittelen tämän reflektion loppupuolella Lockchain-teknologian, joka mahdollistaa tämän.
”Joukkoistettu verkko-oppiminen”-luento esitteli hoitoalan verkkokoulutusta ja ajatuksia siitä, miten oleellista tietoa voitaisiin jakaa. Luennolla korostuivat verkkokoulutuksen hyödyt, kuten esimerkiksi laajan kohderyhmän saavuttaminen, yhteisön hyödyntäminen, riippumattomuus paikasta ja taloudelliset syyt. Kriittisen näkökulman vahvistamiseksi perehdyin verkkokoulutuksen haasteisiin The Network Society -kirjan kautta. Kirjan mukaan verkko-opetuksen oppilaiden on vaikeampi vuorovaikuttaa keskenään, mikä voi olla haaste yhteisön hyödyntämiselle. Ongelmana voi myös olla ohjauksen ja auttamisen rajallisuus; monilla oppilailla ei ole riittävää itsekuria. Lisäksi kirjassa puhutaan sosiaalisesta eristäytymisestä; perinteinen oppilaitos on tapaamisen ja sosialisoinnin paikka ja arkirutiinien luoja. Opiskelun erottaminen perhe-elämästä voi myös olla ongelma joissain tapauksissa. (van Dijk 2012.) Omien kokemusteni mukaan verkko-opiskelu on suhteellisen hyvä opiskelun muoto, mutta verkkoalustan keskustelut muiden opiskelijoiden kanssa jäävät melko lyhyeksi; usein verkkokurssin alustalla keskustellaan minimivaatimusten edellyttämässä laajuudessa. Kasvokkaiset keskustelut venyvät pidemmiksi ja niissä aihetta käsitellään kokemusteni mukaan syvällisemmin.
Luennon jälkeisessä keskusteluosuudesssa todettiin, että Facebook, Uber ja Airbnb voivat kadota tulevaisuudessa, mutta syytä tähän ei spekuloitu sen tarkemmin. Airbnb on tarpeellinen, koska se tarjoaa alustan, jonka kautta voidaan vähentää epävarmuutta tuntemattomien ihmisten välillä (Lampinen & Cheshire 2016). Airbnb on mahdollista toteuttaa ilman yritystä lohkoketjuteknologiaa hyödyntäen. Lockchain on lohkoketju ja kryptovaluutta, jonka on tarkoitus vastata samaan tarpeeseen kuin keskitetty Airbnb; siinä Airbnb:n toiminnot on tarkoitus automatisoida siten, että välittäjätahoa ei enää tarvita. Airbnb:ssä data on siiloutunut vain yrityksen käyttöön, mutta Lockchainissa data on kaikkien käytössä ja kaikkien ylläpitämää. Dataa lisätään, poistetaan tai muutetaan Lockchain-tokenilla, joka on maksu tietokannan käytöstä. Kun asiakas ja majoituksen tarjoaja ovat suoraan yhteydessä toisiinsa tietokannan kautta, jää perinteinen välikäsi pois välistä ja kustannukset pienenevät. Lockchainin esittelyvideo on katsottavissa osoitteessa: https://www.youtube.com/watch?time_continue=135&v=tBWpTOhF2Kw

Lähteet
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Dutton, William (2014) Handbook of Internet Studies.
Lampinen, A., & Cheshire, C. (2016). Hosting via Airbnb: Motivations and financial assurances in monetized network hospitality. In Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems (pp. 1669-1680).

27.11. ALUSTATOIMIJAT JA DATATALOUS

“Datatalous & alustat”-luento esitti vertauskuvallisen kuvan öljynporauslautoista; data on uusi öljy ja suurimmat yritykset ovat nykyään datayrityksiä. Kuten introluennolla todettiin, kuluttajien datasta on tullut arvonluonnin lähde. West (2017) esittelee artikkelissaan datakapitalismia. Toimintamme internetissä jättää digitaalisia jälkiä, jotka kerätään ja joita käytetään käyttäytymisemme ennustamiseen, mainostamiseen ja teknologian kehittämiseen. Datankeruu on pitkälti huomaamatonta, algoritmeja on vaikea ymmärtää (West 2017). Datayritykset kilpailevat alustoista; yritykset kuten esimerkiksi Microsoft, Google ja Apple tarjoavat oman infrastruktuurinsa, käyttöjärjestelmänsä ja ohjelmistonsa. van Dijk (2012) kutsuu tätä toimintamallia kirjassaan totalitaariseksi ambitioksi, jossa käyttäjä pyritään sitomaan yrityksen ekosysteemiin. Yrityksen arvot vaikuttavat siihen, millainen niiden alusta on; nykyajan keskeisenä ohjaavana arvona on datakapitalismi. Datakapitalismia vastaan on perustettu kampanjoita ja teknologioita, kuten esimerkiksi luennolla mainitut King Gafa, DuckDuckgo, Tor-verkko, Bitcoin ja #buytwitter.
”Case Aller Media”-luennolla todettiin sama asia joka on tullut puheeksi jo moneen kertaan tällä kurssilla: kaikki alkaa olla muutaman jätin käsissä. Verkon kontrolli on pitkälti keskittynyt kahden yrityksen, Facebookin ja Googlen haltuun. Erityisesti Google on laajentanut toimintaansa uusille alueille kuten sähköpostipalveluihin (ja niiden skannaamiseen mainostustarkoituksia varten) ja internetin käytön laajamittaiseen seurantaan muun muassa cookies-seurannan avulla (West 2017). Luennolla mainittiin suuri muutos, joka on tulossa liittyen datan hallinnan oikeuksiin. Sääntely on tähän mennessä onnistunut Euroopassa jossain määrin, mutta perustunut lähinnä läpinäkyvyyden lisäämiseen. Mielestäni läpinäkyvyys ei yksinään auta asiaa, koska käyttäjän ainoa vaihtoehto on jättäytyä kokonaan palvelujen ulkopuolelle, mikä vaikeuttaisi elämää. Mitä enemmän verkostoon liittyy ihmisiä, sitä enemmän paineita muilla on liittyä mukaan (The law of network externality, ks. van Dijk 2012). Datajättien toiminta datankeruun osalta ei kuitenkaan ole ainoastaan huono asia, koska datankeruuseen liittyy myös monenlaisia synergiaetuja. Esimerkiksi meille mainostetaan niitä tuotteita, joita todennäköisesti haluamme. Saamme kohdennettua ja meille räätälöityä palvelua. Teknologiaa voidaan myös datan pohjalta kehittää eteenpäin.
Kauppalehden (24.2.2017) kolumnissa esitettiin ajatuksia terveydenhuollon asiakkaiden profiloinnista sosiaalisen median datan perusteella; kolumnin mukaan esimerkiksi luottohakemus voitaisiin tulevaisuudessa hylätä Facebook-päivityksistä tehtyjen terveyskäyttäytymisoletusten perusteella. Mielestäni tällainen teknologia ei kuitenkaan ole oikeudenmukainen, koska siitä kärsivät vain ne jotka ovat sosiaalisen median käyttäjiä. Tietoja ei voida näin ollen kerätä kaikista ihmisistä. Eri ihmisten välillä on lisäksi eroja sen suhteen, kuinka usein ja mitä he julkaisevat sosiaalisessa mediassa. Yksityisviestiketjujen data voisi silti olla suhteellisen luotettava tietolähde yksilöä arvioitaessa useimpien ihmisten tapauksessa.
Testatakseni mitä johtopäätöksiä tekstidatasta voi tehdä, kokeilin IBM:n kielellistä tekoälyohjelmaa Watsonia (Rajoitetusti käytettävissä osoitteessa: https://personality-insights-demo.ng.bluemix.net/). Watsonilla voidaan analysoida tekstin tai twiittien perusteella kirjoittajan persoonallisuuspiirteitä. Kokeilu osoitti, että Watson toimii  hyvänä esimerkkinä siitä miten dataa voidaan analysoida ja tehdä siitä johtopäätöksiä. Tällaisilla analyyseilla voisi olla laajamittaisessa käytössä monia seurauksia: työnantaja voisi esimerkiksi selvittää potentiaalisen työntekijän persoonallisuuspiirteet Twitter-tilin tai työhakemuksen hakemuskirjeen tekstin perusteella. Watson ei ole vielä käytettävissä suomen kielellä, mutta voidaan odottaa, että tulevaisuudessa nämä teknologiat kehittyvät kiihtyvällä tahdilla ja ovat käytettävissä useammalle eri kielelle.  

Lähteet
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Kauppalehti 24.2.2017: Kestääkö segmentti muutoksen? Viitattu  14.12.2017. Saatavissa: https://www.kauppalehti.fi/uutiset/kestaako-segmentti-muutoksen/2gSZGbKr 
West, S. M. (2017). Data capitalism: Redefining the logics of surveillance and privacy. Business & Society, 0007650317718185.


4.12. ALGORITMIT, JULKISUUS JA MEDIA

“Algoritmit, julkisuus ja media”-luento tarkasteli hybridiä mediatilaa ja sen luomaa julkisuutta. Luennon mukaan massamedia, sosiaalinen media ja hakukoneet rakentuvat yhteiseksi julkisuudeksi. Yhtäältä perinteisen median uutisointi vaikuttaa sosiaalisen median keskusteluihin, ja toisaalta perinteinen media poimii uutisoinnin aiheita sosiaalisesta mediasta. Yhtenä esimerkkinä voisin mainita Sami Kiesin tapauksen, jossa hän pääsi YLE:n uutiseen sen jälkeen kun hänestä oli jaettu sosiaaliseen mediaan huhu jonka mukaan hän olisi hakannut silloista tyttöystäväänsä (ks. YLE 8.12.2017). Asiasta oli meuhkannut sosiaalisessa mediassa yli 70 000 ihmistä. Tapaus on tyypillinen esimerkki nykypäivän sosiaalisen median kohun saamasta näkyvyydestä ja osoittaa sen, missä laajuudessa yksityiset tapahtumat voivat saada huomattavaa julkisuutta sosiaalisessa mediassa. Hybridi mediatila on iso tarinakoneisto, kuten luennolla todettiin.
Yhteiskuntamme on muuttunut massayhteiskunnasta verkkoyhteiskunnaksi: massamedia välitti ennen maailmankuvaa traditionaalisille yhteisöille, nyt muodostuu läpileikkaavia virtuaalisia yhteisöjä. Seurauksena on julkisuuden fragmentoituminen ja useiden yksityisyyden alueiden syntyminen. (van Dijk 2012.) Fragmentoitumista edistää omalta osaltaan luennolla ja artikkeleissa esitelty sosiaalinen filtteröinti, joka liittyy huomiotalouden logiikkaan. Koska internetissä on liikaa tietoa (The law of limits to attention, ks. van Dijk 2012), tarvitaan filtteröintiä ja sitä hoitavia tahoja kuten hakukoneita, selaimia, botteja, ohjelmistoja sekä algoritmeja (Willson 2014), jotka pyrkivät kilpailemaan huomiostamme näyttämällä meille haluamaamme sisältöä. Seurauksena ovat niin sanotut kaikukammiot (filter bubbles); uutisvirrassamme tai Googlen hakutuloksissamme näytetään sellaista sisältöä millaista haluamme nähdä. Luennon esimerkissä tuotiin esille, että demokraattien ja republikaanien kannattajat saavat googlatessaan eri hakutuloksia. 
Luennolla mainittiin, että algoritmit ovat yhtä fiksuja tai tyhmiä kuin me; usein vinoumat selittyvät opetusaineistolla eli omalla käyttäytymisellä. Olen kuitenkin eri mieltä asiasta, koska uskon että ihmisen toimintaan pätee polkuriippuvuus; sen sijaan että olisimme tietynlaisia, meistä tulee tietynlaisia. Algoritmit vahvistavat sitä reittiä, jolle olemme sattumalta päätyneet. Jos mietitään esimerkiksi Twitter-botin kiroilua, uskon että kiroilu on yhtälailla opittu ominaisuus, jonka sekä ihmiset että botit voivat oppia polkuriippuvuuden kautta.
“Media, algoritmit ja ennakoiva löytäminen”-luennolla todettiin heti alkuun, että kilpailu huomiostamme kasvaa ja elämme vaihtoehtoisissa algoritmisissa todellisuuksissa. Itse olen aiemmin suhtautunut luottavaisesti hakukoneiden tarjoamaan sisältöön, mutta tästä eteenpäin suhtaudun epäilevästi. Ajatus lukitusnäytöstä seuraavana askeleena uutisvirran jälkeen oli mielenkiintoinen; tosin tuntuu, että nykyhetken ongelma ei ole pelkästään uutisvirrassa vaan informaation yltäkylläisyydessä. Yksi syy, miksi en itse lataa YLE:n uutisvahtia on se, että puhelimessani on liikaa ilmoituksia. Tämä johtuu osittain sovellusten määrän kasvusta. Olen laittanut suurimman osan ilmoituksista äänettömälle. Uutisia luen silloin kun siltä tuntuu, mutta jatkuva ilmoitusten saaminen uutisista ei kiinnosta itseäni.
Päivittäinen elämä delegoidaan yhä suuremmissa määrin online-areenoille. Kun ihmiset delegoivat elämäänsä verkkoon, tämä tarjoaa suuryrityksille kuten Googlelle entistä enemmän mahdollisuuksia hallita ja manipuloida dataa ja käyttäjiä. Emme myöskään voi aina tietää, millaisia odotettuja ja odottamattomia seurauksia delegoimisella on; esimerkiksi ensimmäisen luennon reflektiossa esittelin kulttuurin muutosta verkkodeittailun osalta (ks. introluento). Willsonin (2017) artikkelissa esitetään, että algoritmit vahvistavat stereotypioita ja voivat vaikuttaa ystävyyssuhteisiin, identiteetteihin ja maailmankuvaan. Monet algoritmeista ovat yksityisomisteisia, joten niitä on vaikea kritisoida ja ymmärtää. (Willson 2017.) Luennon kysymysosiossa nostettiin esille ajatus siitä, että algoritmit voivat muodostaa feedback-luuppeja ja synnyttää itseään toteuttavia ennusteita; seurauksena on yksilön käytöksen muuttuminen yksipuoliseksi. Johtuvatko nyky-yhteiskunnan ongelmat algoritmeista, koska näitä ongelmia ei ollut internetin alkuaikoina?
API on sovellus jonka kautta voidaan hakea verkkoalustan tietoja ja antaa sille käskyjä. Sen kautta voidaan esimerkiksi rakentaa botti, jolla voidaan antaa Twitter-tilille käskyjä. Latasin API:n kautta Helsingin Yliopiston Twitter-tilin tiedot. Tiedoista voidaan huomata se mikä on julkista. Taustalla vaikuttavat algoritmit ovat piilotettuina ja suojattuina ja niihin ei pääse käyttöliittymän kautta. Ainut tapa päästä algoritmeihin käsiksi olisi hakkeroitua palvelimille, joten niiden täsmällistä toimintaa on vaikea selvittää ulkopuolisena. Algoritmien selvittäminen ilman hakkerointia vaatisi suuren määrän kokeiluja ja niiden perusteella algoritmien toiminnan päättelemisen. API-sovellus siis osoittaa sen, että algoritmit on piilotettu käyttäjän tai ulkopuolisen asiantuntijan tavoittamattomiin. 

Lähteet
van Dijk, Jan (2012). The Network Society (3rd Ed.). Sage Publications.
Willson, M. (2014). The politics of social filtering. Convergence: The International Journal of Research into New Media Technologies, 20(2), 218–232.
Willson, M. (2017). Algorithms (and the) everyday. Information, Communication & Society, 20(1), 137–150. 
YLE 8.12.2017: Nuori mies alkoi kitkeä kiusaamista kouluista ja sosiaalisesta mediasta – sitten hänet leimattiin naistenhakkaajaksi. Viitattu  14.12.2017. Saatavissa: https://yle.fi/uutiset/3-9968038   
*/
    
}